// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025
// This was done for fun and personal purposes, to get used to AI prompting

#pragma once
#include <vector>
#include <iostream>

void DrawPoints(const std::vector<Point>& points)
{
    if (points.empty()) return;

    // Find bounding box
    int minX = points[0].x, maxX = points[0].x;
    int minY = points[0].y, maxY = points[0].y;

    for (const auto& p : points)
    {
        minX = std::min(minX, p.x);
        maxX = std::max(maxX, p.x);
        minY = std::min(minY, p.y);
        maxY = std::max(maxY, p.y);
    }

    // Create grid
    std::vector<std::vector<char>> grid(maxY - minY + 1, std::vector<char>(maxX - minX + 1, ' '));

    // Draw points
    for (const auto& p : points)
    {
        grid[p.y - minY][p.x - minX] = '*';
    }

    // Print grid
    for (const auto& row : grid)
    {
        for (char c : row)
        {
            std::cout << c;
        }
        std::cout << std::endl;
    }
}
