// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025
// for prompting practice

// BasicRemote.hpp
#ifndef BASIC_REMOTE_HPP
#define BASIC_REMOTE_HPP

#include "RemoteControl.hpp"
#include <iostream>

class BasicRemote : public RemoteControl {
private:
    bool isOn = false;

public:
    BasicRemote(Device* dev) : RemoteControl(dev) {}

    void togglePower() override {
        if (isOn) {
            device->turnOff();
            isOn = false;
        } else {
            device->turnOn();
            isOn = true;
        }
    }
};

#endif // BASIC_REMOTE_HPP
