// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025
// for prompting practice

// Device.hpp
#ifndef DEVICE_HPP
#define DEVICE_HPP

class Device {
public:
    virtual ~Device() = default;
    virtual void turnOn() = 0;
    virtual void turnOff() = 0;
};

#endif // DEVICE_HPP
