// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025
// for prompting practice

// main.cpp
#include "TV.hpp"
#include "Radio.hpp"
#include "BasicRemote.hpp"

int main() {
    TV tv;
    Radio radio;

    BasicRemote remoteForTV(&tv);
    BasicRemote remoteForRadio(&radio);

    std::cout << "Using Remote on TV:" << std::endl;
    remoteForTV.togglePower();
    remoteForTV.togglePower();

    std::cout << "\nUsing Remote on Radio:" << std::endl;
    remoteForRadio.togglePower();
    remoteForRadio.togglePower();

    return 0;
}
