// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025
// for prompting practice

// RemoteControl.hpp
#ifndef REMOTE_CONTROL_HPP
#define REMOTE_CONTROL_HPP

#include "Device.hpp"

class RemoteControl {
protected:
    Device* device;  // Bridge to implementation
    // pointer to Device, allowing it to work with any Device implementation
    // It does not define how a device works—only how to control it.

public:
    RemoteControl(Device* dev) : device(dev) {}
    virtual ~RemoteControl() = default;

    virtual void togglePower() = 0;
};

#endif // REMOTE_CONTROL_HPP
