// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025
// for prompting practice

// TV.hpp
#ifndef TV_HPP
#define TV_HPP

#include "Device.hpp"
#include <iostream>

class TV : public Device {
public:
    void turnOn() override {
        std::cout << "TV is now ON." << std::endl;
    }

    void turnOff() override {
        std::cout << "TV is now OFF." << std::endl;
    }
};

#endif // TV_HPP
