// Disclaimer: This file is entirely
// Generated by OpenAI's ChatGPT-4, February 2025

#include <iostream>
#include <memory> // For shared_ptr

class MyClass {
public:
    MyClass() { std::cout << "MyClass Constructor\n"; }
    ~MyClass() { std::cout << "MyClass Destructor\n"; }

    void display() { std::cout << "Hello from MyClass\n"; }
};

int main() {
    // Creating a shared_ptr to manage the object
    std::shared_ptr<MyClass> ptr1 = std::make_shared<MyClass>();
    {
        // ptr2 shares ownership with ptr1
        std::shared_ptr<MyClass> ptr2 = ptr1;
        ptr2->display();  // Both ptr1 and ptr2 can access the object

        std::cout << "ptr2 going out of scope\n";
    } // ptr2 is destroyed here, but ptr1 still owns the object

    std::cout << "ptr1 going out of scope\n";
    // Object is deleted automatically when the last shared_ptr goes out of scope

    return 0;
}
